mode = "fastest"

[light_sources]
	water_sensitive_check = false
	block_entities = false
	entities = false
	self = true
	tnt = "simple"
	creeper = "simple"
	beam = true
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				player = true
				allay = true
				area_effect_cloud = true
				armor_stand = true
				arrow = true
				axolotl = true
				bat = true
				bee = true
				blaze = true
				block_display = true
				boat = true
				camel = true
				cat = true
				cave_spider = true
				chicken = true
				cod = true
				cow = true
				creeper = true
				dolphin = true
				dragon_fireball = true
				drowned = true
				end_crystal = true
				enderman = true
				endermite = true
				evoker = true
				evoker_fangs = true
				experience_orb = true
				eye_of_ender = true
				falling_block = true
				fireball = true
				firework_rocket = true
				fishing_bobber = true
				fox = true
				frog = true
				ghast = true
				giant = true
				glow_item_frame = true
				glow_squid = true
				goat = true
				guardian = true
				hoglin = true
				husk = true
				illusioner = true
				interaction = true
				iron_golem = true
				item = true
				item_display = true
				item_frame = true
				leash_knot = true
				lightning_bolt = true
				llama = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				command_block_minecart = true
				furnace_minecart = true
				spawner_minecart = true
				tnt_minecart = true
				mooshroom = true
				ocelot = true
				painting = true
				panda = true
				parrot = true
				phantom = true
				pig = true
				piglin = true
				piglin_brute = true
				pillager = true
				polar_bear = true
				potion = true
				tnt = true
				pufferfish = true
				rabbit = true
				ravager = true
				salmon = true
				sheep = true
				shulker = true
				shulker_bullet = true
				silverfish = true
				skeleton = true
				slime = true
				small_fireball = true
				sniffer = true
				snow_golem = true
				snowball = true
				spectral_arrow = true
				spider = true
				squid = true
				stray = true
				strider = true
				tadpole = true
				text_display = true
				experience_bottle = true
				egg = true
				ender_pearl = true
				trader_llama = true
				trident = true
				tropical_fish = true
				turtle = true
				vex = true
				vindicator = true
				warden = true
				witch = true
				wither_skeleton = true
				wither_skull = true
				wolf = true
				zoglin = true
				zombie = true
				zombie_villager = true
				zombified_piglin = true
				chest_minecart = true
				chest_boat = true
				hopper_minecart = true
				elder_guardian = true
				ender_dragon = true
				wither = true
				mule = true
				horse = true
				donkey = true
				zombie_horse = true
				skeleton_horse = true
				villager = true
				wandering_trader = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				biplane = true
				cargo_airship = true
				gyrodyne = true
				quadrocopter = true
				warship = true
				bullet = true
				tiny_tnt = true

			[light_sources.settings.entities.bettertrims]
				ancient_skeleton = true

			[light_sources.settings.entities.deeperdarker]
				angler_fish = true
				boat = true
				chest_boat = true
				sculk_centipede = true
				sculk_leech = true
				sculk_snapper = true
				shattered = true
				shriek_worm = true
				sludge = true
				stalker = true

			[light_sources.settings.entities.spell_engine]
				spell_area_effect = true
				spell_projectile = true

			[light_sources.settings.entities.paladins]
				barrier = true
				battle_banner = true

			[light_sources.settings.entities.biomesoplenty]
				boat = true
				chest_boat = true

			[light_sources.settings.entities.supplementaries]
				brick_projectile = true
				cannonball = true
				falling_ash = true
				falling_urn = true
				hat_stand = true
				dispenser_minecart = true
				red_merchant = true
				rope_arrow = true
				slimeball_projectile = true
				slingshot_projectile = true
				bomb = true
				falling_sack = true
				pearl_marker = true

			[light_sources.settings.entities.smallships]
				brigg = true
				cog = true
				drakkar = true
				galley = true
				cannon_ball = true

			[light_sources.settings.entities.betterend]
				cubozoa = true
				dragonfly = true
				end_fish = true
				end_slime = true
				shadow_walker = true
				silk_moth = true

			[light_sources.settings.entities.simplyskills]
				dreadglare = true
				greater_dreadglare = true
				wraith = true
				custom_entity_1 = true

			[light_sources.settings.entities.duckling]
				duck = true
				duck_egg = true
				quackling = true

			[light_sources.settings.entities.handcrafted]
				fancy_painting = true
				seat = true

			[light_sources.settings.entities.betternether]
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				jungle_skeleton = true
				naga = true
				naga_projectile = true
				skull = true

			[light_sources.settings.entities.yungscavebiomes]
				ice_cube = true
				icicle = true
				sand_snapper = true

			[light_sources.settings.entities.items_displayed]
				item_display = true
				jewelry_pillow = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.amendments]
				falling_lantern = true

			[light_sources.settings.entities.bclib]
				chair = true

			[light_sources.settings.entities.brutalbosses]
				thrownitem = true

			[light_sources.settings.entities.mcwfurnitures]
				chair_entity = true

			[light_sources.settings.entities.moborigins]
				origin_slime = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.shield_overhaul]
				shield_bash_entity = true

			[light_sources.settings.entities.simplyswords]
				battlestandard = true
				battlestandarddark = true
				simplybeeentity = true

			[light_sources.settings.entities.sit]
				entity_sit = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false
