
[Visual]
	"Popup Gui" = true
	"Show Beastiary Entries by default" = false
	"Do Progression Break Punishment" = true

[Gameplay]
	"Block Breaking" = true
	"Quicktime Events" = true
	"Mangled Mobs" = true
	"Higher Omen Spawns" = false
	"Do mangled creeper exploding" = true

